-- =============================================================================
-- create_tables.sql
-- StormersChat — Neon PostgreSQL schema for all 15 Oval Insights tables
-- Run this in the Neon SQL Editor before loading CSVs.
-- =============================================================================

-- ── Core reference tables ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS matches (
  match_id          INTEGER PRIMARY KEY,
  date_time         TEXT,
  season_id         INTEGER,
  season_name       TEXT,
  competition_id    INTEGER,
  competition       TEXT,
  round             INTEGER,
  match_status      TEXT,
  finalised         INTEGER,
  home_team_id      INTEGER,
  home_team         TEXT,
  home_team_short   TEXT,
  home_team_abbr    TEXT,
  home_score_ht     INTEGER,
  home_score_ft     INTEGER,
  away_team_id      INTEGER,
  away_team         TEXT,
  away_team_short   TEXT,
  away_team_abbr    TEXT,
  away_score_ht     INTEGER,
  away_score_ft     INTEGER,
  winner_team_id    INTEGER,
  venue             TEXT,
  venue_id          INTEGER,
  venue_country     TEXT,
  venue_timezone    TEXT,
  venue_floodlit    INTEGER,
  neutral_venue     INTEGER,
  attendance        INTEGER
);

CREATE TABLE IF NOT EXISTS players (
  player_id  INTEGER PRIMARY KEY,
  name       TEXT,
  known_name TEXT,
  first_name TEXT,
  last_name  TEXT
);

CREATE TABLE IF NOT EXISTS venues (
  competition_id  INTEGER,
  competition     TEXT,
  venue_id        INTEGER,
  venue_name      TEXT,
  location        TEXT,
  country_id      INTEGER,
  country         TEXT,
  timezone        TEXT,
  capacity        INTEGER,
  roof            TEXT,
  surface         TEXT,
  year_built      INTEGER,
  latitude        DOUBLE PRECISION,
  longitude       DOUBLE PRECISION,
  PRIMARY KEY (competition_id, venue_id)
);

CREATE TABLE IF NOT EXISTS officials (
  competition_id  INTEGER,
  competition     TEXT,
  official_id     INTEGER,
  first_name      TEXT,
  last_name       TEXT,
  known_name      TEXT,
  initials        TEXT,
  gender          TEXT,
  dob             TEXT,
  country         TEXT,
  PRIMARY KEY (competition_id, official_id)
);

CREATE TABLE IF NOT EXISTS squad (
  competition_id   INTEGER,
  competition      TEXT,
  team_id          INTEGER,
  team_name        TEXT,
  player_id        INTEGER,
  player_name      TEXT,
  known_name       TEXT,
  first_name       TEXT,
  last_name        TEXT,
  position         TEXT,
  gender           TEXT,
  date_of_birth    TEXT,
  birthplace       TEXT,
  country_of_birth TEXT,
  national_team    TEXT,
  height_cm        DOUBLE PRECISION,
  weight_kg        DOUBLE PRECISION,
  PRIMARY KEY (competition_id, team_id, player_id)
);

-- ── Match-level stats ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS player_match_stats (
  id                          SERIAL PRIMARY KEY,
  match_id                    INTEGER REFERENCES matches(match_id),
  player_id                   INTEGER REFERENCES players(player_id),
  player_name                 TEXT,
  team_id                     INTEGER,
  team_name                   TEXT,
  is_home_team                INTEGER,
  position_id                 INTEGER,
  position_name               TEXT,
  shirt_number                INTEGER,
  minutes_played              INTEGER,
  minutes_played_first_half   INTEGER,
  minutes_played_second_half  INTEGER,
  tries_scored                INTEGER,
  points_scored               INTEGER,
  conversions_made            INTEGER,
  penalties_made              INTEGER,
  drop_goals_made             INTEGER,
  penalties_conceded          INTEGER,
  yellow_cards                INTEGER,
  red_cards                   INTEGER,
  carries                     INTEGER,
  metres_made                 INTEGER,
  passes                      INTEGER,
  defenders_beaten            INTEGER,
  crossed_gainline            INTEGER,
  failed_gainline             INTEGER,
  turnovers_conceded          INTEGER,
  post_contact_metres         INTEGER,
  try_assists                 INTEGER,
  break_assists               INTEGER,
  tackles_made                INTEGER,
  tackles_missed              INTEGER,
  total_tackles_attempted     INTEGER,
  tackle_success_pct          DOUBLE PRECISION,
  turnovers_won               INTEGER,
  jackals                     INTEGER,
  dominant_tackles            INTEGER,
  lineout_throws_won          INTEGER,
  lineout_throws_lost         INTEGER,
  lineout_won_clean           INTEGER,
  lineout_won_other           INTEGER,
  throw_front                 INTEGER,
  throw_middle                INTEGER,
  throw_back                  INTEGER,
  kicks_in_play               INTEGER,
  kick_metres                 INTEGER,
  territorial_kicks           INTEGER,
  ruck_entries_attacking      INTEGER,
  ruck_entries_defensive      INTEGER,
  ruck_entries_total          INTEGER,
  ruck_nuisance               INTEGER,
  scrum_involvement_total     INTEGER,
  scrum_won_total             INTEGER,
  scrum_won_penalty           INTEGER,
  scrum_won_outright          INTEGER,
  defensive_catches           INTEGER,
  defensive_catch_success     INTEGER,
  restart_catches             INTEGER,
  restart_catch_success       INTEGER
);

CREATE TABLE IF NOT EXISTS match_team_stats (
  id                      SERIAL PRIMARY KEY,
  match_id                INTEGER REFERENCES matches(match_id),
  team_id                 INTEGER,
  team_name               TEXT,
  is_home_team            INTEGER,
  carries                 INTEGER,
  metres_made             INTEGER,
  passes                  INTEGER,
  defenders_beaten        INTEGER,
  clean_breaks            INTEGER,
  crossed_gainline        INTEGER,
  failed_gainline         INTEGER,
  offloads                INTEGER,
  post_contact_metres     INTEGER,
  try_assists             INTEGER,
  tries_scored            INTEGER,
  points_scored           INTEGER,
  conversions_made        INTEGER,
  penalties_made          INTEGER,
  tackles_made            INTEGER,
  tackles_missed          INTEGER,
  total_tackles_attempted INTEGER,
  tackle_success_pct      DOUBLE PRECISION,
  turnovers_won           INTEGER,
  dominant_tackles        INTEGER,
  lineout_throws_won      INTEGER,
  lineout_throws_lost     INTEGER,
  lineout_success_pct     DOUBLE PRECISION,
  scrum_won               INTEGER,
  scrum_lost              INTEGER,
  scrum_success_pct       DOUBLE PRECISION,
  kicks_in_play           INTEGER,
  kick_metres             INTEGER,
  penalties_conceded      INTEGER,
  rucks_won               INTEGER,
  rucks_lost              INTEGER,
  mauls_won               INTEGER,
  mauls_lost              INTEGER,
  maul_success_pct        DOUBLE PRECISION,
  visits_to_22            INTEGER,
  points_from_22_visits   INTEGER,
  possession_pct          DOUBLE PRECISION,
  possession_pct_fh       DOUBLE PRECISION,
  possession_pct_sh       DOUBLE PRECISION,
  territory_pct           DOUBLE PRECISION,
  territory_pct_fh        DOUBLE PRECISION,
  territory_pct_sh        DOUBLE PRECISION,
  total_restarts          INTEGER,
  restarts_retained       INTEGER,
  restarts_50m            INTEGER,
  restarts_goal_line      INTEGER,
  restart_success_pct     DOUBLE PRECISION,
  attacking_catches       INTEGER,
  attacking_catch_success INTEGER,
  defensive_catches       INTEGER,
  defensive_catch_success INTEGER,
  restart_catches         INTEGER,
  restart_catch_success   INTEGER,
  aerial_contests         INTEGER,
  aerial_contests_won     INTEGER,
  aerial_contest_pct      DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS match_events (
  id             SERIAL PRIMARY KEY,
  match_id       INTEGER REFERENCES matches(match_id),
  event_id       INTEGER,
  event_type     TEXT,
  event_type_id  INTEGER,
  time           TEXT,
  minute         INTEGER,
  second         INTEGER,
  period         TEXT,
  team_id        INTEGER,
  team_name      TEXT,
  player_id      INTEGER,
  player_name    TEXT,
  score_home     INTEGER,
  score_away     INTEGER,
  start_x        DOUBLE PRECISION,
  start_y        DOUBLE PRECISION,
  end_x          DOUBLE PRECISION,
  end_y          DOUBLE PRECISION,
  direction      TEXT,
  properties     TEXT,
  is_deleted     INTEGER,
  timestamp      TEXT,
  last_modified  TEXT
);

CREATE TABLE IF NOT EXISTS match_quarters (
  id               SERIAL PRIMARY KEY,
  match_id         INTEGER REFERENCES matches(match_id),
  quarter          TEXT,
  home_team_id     INTEGER,
  home_team_name   TEXT,
  away_team_id     INTEGER,
  away_team_name   TEXT,
  stat_key         TEXT,
  stat_label       TEXT,
  home_value       DOUBLE PRECISION,
  away_value       DOUBLE PRECISION,
  home_share_pct   DOUBLE PRECISION,
  away_share_pct   DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS head_to_head (
  match_id             INTEGER PRIMARY KEY REFERENCES matches(match_id),
  home_team_id         INTEGER,
  home_team_name       TEXT,
  away_team_id         INTEGER,
  away_team_name       TEXT,
  total_matches        INTEGER,
  home_wins            INTEGER,
  away_wins            INTEGER,
  draws                INTEGER,
  home_win_pct         DOUBLE PRECISION,
  away_win_pct         DOUBLE PRECISION,
  draw_pct             DOUBLE PRECISION,
  biggest_win_margin   INTEGER,
  wins_at_venue        INTEGER,
  neutral_wins         INTEGER,
  total_points_scored  INTEGER,
  total_tries_scored   INTEGER,
  last_5_matches       TEXT,
  form                 TEXT
);

-- ── Season-aggregate tables ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS standings (
  competition_id    INTEGER,
  competition       TEXT,
  season_id         INTEGER,
  position          INTEGER,
  team_id           INTEGER,
  team_name         TEXT,
  team_short_name   TEXT,
  played            INTEGER,
  won               INTEGER,
  drawn             INTEGER,
  lost              INTEGER,
  byes              INTEGER,
  points_for        INTEGER,
  points_against    INTEGER,
  point_diff        INTEGER,
  tries_for         INTEGER,
  tries_against     INTEGER,
  bonus_pts_win     INTEGER,
  bonus_pts_try     INTEGER,
  bonus_pts_loss    INTEGER,
  league_points     INTEGER,
  points_percentage DOUBLE PRECISION,
  points_scored_pct DOUBLE PRECISION,
  PRIMARY KEY (competition_id, team_id)
);

CREATE TABLE IF NOT EXISTS round_standings (
  id                SERIAL PRIMARY KEY,
  competition_id    INTEGER,
  competition       TEXT,
  season_id         INTEGER,
  round             INTEGER,
  position          INTEGER,
  team_id           INTEGER,
  team_name         TEXT,
  team_short_name   TEXT,
  played            INTEGER,
  won               INTEGER,
  drawn             INTEGER,
  lost              INTEGER,
  byes              INTEGER,
  points_for        INTEGER,
  points_against    INTEGER,
  point_diff        INTEGER,
  tries_for         INTEGER,
  tries_against     INTEGER,
  bonus_pts_win     INTEGER,
  bonus_pts_try     INTEGER,
  bonus_pts_loss    INTEGER,
  league_points     INTEGER,
  points_percentage DOUBLE PRECISION,
  points_scored_pct DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS season_stats (
  competition_id          INTEGER,
  competition             TEXT,
  season_id               INTEGER,
  team_id                 INTEGER,
  team_name               TEXT,
  total_carries           INTEGER,
  total_metres_made       INTEGER,
  total_passes            INTEGER,
  total_clean_breaks      INTEGER,
  total_defenders_beaten  INTEGER,
  total_try_assists       INTEGER,
  total_offloads          INTEGER,
  total_turnovers_conceded INTEGER,
  total_post_contact_metres INTEGER,
  total_break_assists     INTEGER,
  total_dominant_carries  INTEGER,
  total_carry_distance    INTEGER,
  total_metres_in_contact INTEGER,
  total_crossed_gainline  INTEGER,
  total_failed_gainline   INTEGER,
  total_handling_errors   INTEGER,
  total_errors            INTEGER,
  total_tries             INTEGER,
  total_points            INTEGER,
  total_conversions       INTEGER,
  total_penalties_made    INTEGER,
  total_missed_conversions INTEGER,
  total_missed_penalties  INTEGER,
  total_penalty_tries     INTEGER,
  goal_success_pct        DOUBLE PRECISION,
  total_tackles_made      INTEGER,
  total_tackles_missed    INTEGER,
  tackle_success_pct      DOUBLE PRECISION,
  total_turnovers_won     INTEGER,
  lineout_throws_won      INTEGER,
  lineout_success_pct     DOUBLE PRECISION,
  total_kicks_in_play     INTEGER,
  total_kick_metres       INTEGER,
  scrums_won              INTEGER,
  scrum_success_pct       DOUBLE PRECISION,
  total_penalties_con     INTEGER,
  total_yellow_cards      INTEGER,
  total_red_cards         INTEGER,
  rucks_won               INTEGER,
  rucks_lost              INTEGER,
  mauls_won               INTEGER,
  mauls_lost              INTEGER,
  maul_success_pct        DOUBLE PRECISION,
  visits_to_22            INTEGER,
  points_from_22_visits   INTEGER,
  possession_pct          DOUBLE PRECISION,
  territory_pct           DOUBLE PRECISION,
  total_restarts          INTEGER,
  restarts_retained       INTEGER,
  restart_success_pct     DOUBLE PRECISION,
  attacking_catches       INTEGER,
  attacking_catch_success INTEGER,
  defensive_catches       INTEGER,
  restart_catches         INTEGER,
  aerial_contests         INTEGER,
  aerial_contests_won     INTEGER,
  aerial_contest_pct      DOUBLE PRECISION,
  ruck_entries_attacking  INTEGER,
  ruck_entries_defensive  INTEGER,
  ruck_entries_total      INTEGER,
  ruck_nuisance           INTEGER,
  ruck_nuisance_jackal    INTEGER,
  PRIMARY KEY (competition_id, team_id)
);

-- ── Leaderboard tables ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS player_top10 (
  id              SERIAL PRIMARY KEY,
  competition_id  INTEGER,
  competition     TEXT,
  stat_name       TEXT,
  stat_api_key    TEXT,
  metric_type     TEXT,
  rank            INTEGER,
  player_id       INTEGER,
  player_name     TEXT,
  team_id         INTEGER,
  team_name       TEXT,
  appearances     INTEGER,
  minutes_played  INTEGER,
  stat_value      DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS team_top_stats (
  id              SERIAL PRIMARY KEY,
  competition_id  INTEGER,
  competition     TEXT,
  stat_name       TEXT,
  stat_api_key    TEXT,
  metric_type     TEXT,
  rank            INTEGER,
  team_id         INTEGER,
  team_name       TEXT,
  stat_value      DOUBLE PRECISION
);

-- ── Indexes for common query patterns ────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pms_match    ON player_match_stats(match_id);
CREATE INDEX IF NOT EXISTS idx_pms_player   ON player_match_stats(player_id);
CREATE INDEX IF NOT EXISTS idx_pms_team     ON player_match_stats(team_id);
CREATE INDEX IF NOT EXISTS idx_mts_match    ON match_team_stats(match_id);
CREATE INDEX IF NOT EXISTS idx_mts_team     ON match_team_stats(team_id);
CREATE INDEX IF NOT EXISTS idx_events_match ON match_events(match_id);
CREATE INDEX IF NOT EXISTS idx_events_type  ON match_events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_team  ON match_events(team_id);
CREATE INDEX IF NOT EXISTS idx_quarters_match ON match_quarters(match_id);
CREATE INDEX IF NOT EXISTS idx_matches_comp ON matches(competition_id, season_id);
